filename: parsedProducts.csv
url: https://www.petsonic.com/dermatitis-y-problemas-piel-para-perros/
product_per_page: 25
xpath_name: //h1[@class = "product_main_name"]
xpath_price_per_weight: //span[@class = "price_comb"]
xpath_weight_variation: //span[@class = "radio_label"]
xpath_img: //img[@id = "bigpic"]/@src
xpath_product_page: //div[@class = "product-desc display_sd"]//@href
xpath_total_count: //span[@class = "af-total-count"]